### ISSUE TITLE
Some endpoint require 2 permissions

### ISSUE THREAD

**Issue by fehlmach** [merill/graph-permissions-explorer#1]
Hi there

I really like your site and was looking for something like this for a long time.
I have a suggestion for improvement. There are endpoints which require two permissions and currently the endpoint shows up on both permissions. It would be nice if there is a notice that states that an additional permission is required to call this endpoint. 
For example: Policy.Read.All
Where calling DELETE /applications/{id}/tokenIssuancePolicies/{id}/$ref requires Policy.Read.All **and** Application.ReadWrite.All
Suggestion: State this entry on both Policy.Read.All and Application.ReadWrite.All but have an additional column "also requires" and then add the other permission

Best Regards
Christian

**Comment by merill** [comment]
Thanks for the feedback @fehlmach. This is on my todo list, your suggestion of adding it as 'also requires' is a good idea.

**Comment by merill** [comment]
Sorry it took so long, but this is fixed now!
