### ISSUE TITLE
Awesome tool! Does it work by parsing the URL of doc? Is it possible to also map to PowerShell cmd?

### ISSUE THREAD

**Issue by zhangqiuyang** [merill/graph-permissions-explorer#3]
Awesome tool!! Thanks for it!! I am looking for such a tool for a long time! 
I am wondering does it work by parsing the link "https://docs.microsoft.com/en-us/graph/api/resources/*"? 

I am also looking for a tool which show the mapping between PowerShell cmd and Graph API, any insight for it?😆
such as Get-AzureAdServiceprincipal actually call the AAD Graph API https://graph.windows.net/998a93de-2bd2-4914-b334-c863b40c3638/servicePrincipals?api-version=1.6 ?

**Comment by merill** [comment]
Yes it is based on the docs. See source at https://github.com/merill/GraphPermission
