### ISSUE TITLE
missing API calls 

### ISSUE THREAD

**Issue by meikestone** [merill/graph-permissions-explorer#4]
Hello Merill, 
really nice tool. 
I did a revers search for "Reports.Read.All" (https://graphpermissions.merill.net/permission/Reports.Read.All.html) and was expecting to find "getOffice365ActivationsUserDetail" (https://docs.microsoft.com/en-us/graph/api/reportroot-getoffice365activationsuserdetail?view=graph-rest-1.0) there.
I'm wrong? If the list is not reliable, then it is not a good point to work with (as developer)  ... 
Thanks for Work!!!
Meike

**Comment by merill** [comment]
This has been fixed now.
