### ISSUE TITLE
New Onboarding Permission(Bookmark.Read.All&Acronym.Read.All) Does Not Any Graph Methods Published

### ISSUE THREAD

**Issue by ZChristine** [merill/graph-permissions-explorer#5]
New Onboarding Permission(Bookmark.Read.All&Acronym.Read.All) Does Not Any Graph Methods Published. The question is that why there are no mehthods being published for that and how to add the corresponding permission. 
https://graphpermissions.merill.net/permission/Bookmark.Read.All.html
https://graphpermissions.merill.net/permission/Acronym.Read.All.html

**Comment by merill** [comment]
It looks like there is the /search/query API method included for this scope. Are there others you are seeing?
