### ISSUE TITLE
Missing methods for Member.Read.Hidden permission

### ISSUE THREAD

**Issue by MartinM85** [merill/graph-permissions-explorer#6]
[Member.Read.Hidden](https://graphpermissions.merill.net/permission/Member.Read.Hidden) is missing methods

- read members of hidden administrative unit. See [the note](https://learn.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-1.0&tabs=http#permissions)
- list a user's direct memberships. See [the note](https://learn.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http#permissions)

**Comment by MartinM85** [comment]
Still issue in new version of the site.

**Comment by merill** [comment]
@MartinM85  thanks for raising this. It's fixed now!
