### ISSUE TITLE
Systemic parsing issue from the documentation results in false and missing information

### ISSUE THREAD

**Issue by emiliensocchi** [merill/graph-permissions-explorer#9]
There seems to be a systemic issue with the way information is parsed from the Microsoft documentation, which leads to the following 2 issues:

**1. Many permissions report that "This permission does not have any graph methods published.", although it's not the case.**

A few examples are (there are many more):
- `PrivilegedEligibilitySchedule.ReadWrite.AzureADGroup`
  - Has APIs here at least: https://learn.microsoft.com/en-us/graph/api/privilegedaccessgroup-list-eligibilityschedulerequests?view=graph-rest-beta&tabs=http
- `RoleEligibilitySchedule.ReadWrite.Directory`
  - Has APIs here at least:  https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleeligibilityschedulerequests?view=graph-rest-beta&tabs=http
- `AccessReview.ReadWrite.All`
  - Has APIs here at least: https://learn.microsoft.com/en-us/graph/api/accessreviewinstance-update?view=graph-rest-beta&tabs=http 

**2. Some permissions on Permission Explorer exist in different versions, although they do not exist in reality**

An example of this issue is the `Directory.ReadWrite.All` permission. Permission Explorer shows that the permission exists in three versions as follows:
![image](https://github.com/user-attachments/assets/7a9fb4d1-b4e2-4ea5-b4da-972cb9aabb6f)

However `Directory.ReadWrite.All1` and `Directory.ReadWrite.All2` do not exist. It seems that they were parsed from parts of the documentation where the permission is using superscript. Here is an example: https://learn.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-1.0&tabs=http
![image](https://github.com/user-attachments/assets/7a75a50a-4333-413e-bc71-e413c73c988d)

**Comment by merill** [comment]
Fixed now!
